name: Send Weather Forecast

on:
  schedule:
    # Runs "at minute 55 past every hour" (see https://crontab.guru)
    - cron: "2 8 * * *"
  push:
    branches:
      - "main"

jobs:
  send-weather-forecast:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed

      - name: send weather forecast
        run: |
          pip install -r requirements.txt
          python send.py ${{ secrets.MAIL_USERNAME }} ${{ secrets.MAIL_APP_PASSWORD }}
